# Generated by Django 4.2.29 on 2026-04-04 02:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('zone', models.CharField(choices=[('hyderabad_central', 'Hyderabad Central'), ('banjara_hills', 'Banjara Hills'), ('jubilee_hills', 'Jubilee Hills'), ('secunderabad', 'Secunderabad'), ('hitec_city', 'HITEC City'), ('gachibowli', 'Gachibowli'), ('lb_nagar', 'LB Nagar'), ('kukatpally', 'Kukatpally')], default='hyderabad_central', max_length=30)),
                ('joined_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('risk_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='low', max_length=10)),
                ('fraud_score', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
                ('behavior_score', models.FloatField(default=1.0)),
                ('gps_anomalies', models.IntegerField(default=0)),
                ('max_speed_kmh', models.FloatField(default=30.0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device_id', models.CharField(blank=True, max_length=50)),
                ('avg_daily_earnings', models.FloatField(default=600.0)),
                ('deliveries_per_day', models.IntegerField(default=8)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Delivery Partner',
                'db_table': 'delivery_partners',
            },
        ),
        migrations.CreateModel(
            name='InsurancePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('weekly_premium', models.DecimalField(decimal_places=2, max_digits=6)),
                ('daily_coverage', models.DecimalField(decimal_places=2, max_digits=8)),
                ('description', models.TextField()),
                ('covers_rain', models.BooleanField(default=True)),
                ('covers_aqi', models.BooleanField(default=False)),
                ('covers_curfew', models.BooleanField(default=False)),
                ('covers_cyclone', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'insurance_plans',
            },
        ),
        migrations.CreateModel(
            name='ParametricEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('rain', 'Heavy Rain'), ('aqi', 'AQI Spike'), ('curfew', 'Zone Curfew'), ('cyclone', 'Cyclone Alert'), ('flood', 'Flood Warning')], max_length=15)),
                ('zone', models.CharField(max_length=30)),
                ('threshold', models.CharField(max_length=50)),
                ('value', models.FloatField()),
                ('triggered', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('affected_users', models.IntegerField(default=0)),
                ('total_payout', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'db_table': 'parametric_events',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=15)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('premium_paid', models.DecimalField(decimal_places=2, max_digits=6)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insurance.insuranceplan')),
            ],
            options={
                'db_table': 'subscriptions',
            },
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('released', 'Released'), ('delayed', 'Delayed'), ('blocked', 'Blocked')], default='pending', max_length=10)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.parametricevent')),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payouts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GPSLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('speed_kmh', models.FloatField(default=0)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('anomaly_type', models.CharField(blank=True, max_length=50)),
                ('partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gps_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'gps_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FraudAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('gps_teleport', 'GPS Teleportation'), ('overspeed', 'Speed Anomaly'), ('shared_device', 'Shared Device Ring'), ('ip_cluster', 'IP Cluster'), ('sync_payout', 'Synchronized Payout'), ('static_spoof', 'Static GPS Spoofing')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=10)),
                ('description', models.TextField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('admin_notes', models.TextField(blank=True)),
                ('partners', models.ManyToManyField(related_name='fraud_alerts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'fraud_alerts',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AdminActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('monitor', 'Set Monitor'), ('delay_payout', 'Delay Payout'), ('block', 'Block Account'), ('unblock', 'Unblock Account'), ('resolve_alert', 'Resolve Alert'), ('manual_payout', 'Manual Payout')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admin_actions', to=settings.AUTH_USER_MODEL)),
                ('alert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insurance.fraudalert')),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'admin_action_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
